### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by maximilianoforlenza** [gucompi/ReduxABMEscuela#1]
I have some comments about your code:

- Don't use spanglish. Write all code in Spanish or all code in English. We use English to code

- You must not mutate state directly in the reducer. See the doc https://redux.js.org/basics/reducers

- Use `key` when you do a map. See the doc https://reactjs.org/docs/lists-and-keys.html#keys

- If you don't use state in the component you should use function component instead of class

- Indent code. Is very hard to read. I recommend use eslint or prettier.

- Don't use ref is unnecessary, use onChange prop 

- componentWillUpdate will be deprecated in react 17 and in react 16.x change to unsafe. See the doc https://reactjs.org/docs/react-component.html#unsafe_componentwillupdate

**Comment by gucompi** [comment]
> I have some comments about your code:
> 
> * Don't use spanglish. Write all code in Spanish or all code in English. We use English to code
> * You must not mutate state directly in the reducer. See the doc https://redux.js.org/basics/reducers
> * Use `key` when you do a map. See the doc https://reactjs.org/docs/lists-and-keys.html#keys
> * If you don't use state in the component you should use function component instead of class
> * Indent code. Is very hard to read. I recommend use eslint or prettier.
> * Don't use ref is unnecessary, use onChange prop
> * componentWillUpdate will be deprecated in react 17 and in react 16.x change to unsafe. See the doc https://reactjs.org/docs/react-component.html#unsafe_componentwillupdate

Gracias.
Fueron arreglados los siguientes puntos con la metodologia aclarada:

* You must not mutate state directly in the reducer. See the doc https://redux.js.org/basics/reducers
 Al Agregar un objeto en el state, ahora uso el operador "..."

*Use key when you do a map. See the doc https://reactjs.org/docs/lists-and-keys.html#keys
Fueron agregados "KEY" en cada iteracion al renderizar.

*Indent code. Is very hard to read. I recommend use eslint or prettier.
Fue agregado indentado de ESLINT. Gracias!

*componentWillUpdate will be deprecated in react 17 and in react 16.x change to unsafe. See the doc https://reactjs.org/docs/react-component.html#unsafe_componentwillupdate

Fue reemplazado componentWillUpdate  por UNSAFE_componentWillUpdate 


Gracias por todas las sugerencias!
Saludos, Gustavo.
